language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=pypy
install:
  - pip install tox
  - pip install python-coveralls
script:
  - tox -e $TOX_ENV
services:
  - couchdb
after_success:
  - coveralls --data_file test/.coverage
